<a href="https://colab.research.google.com/github/delowerhossentuhin/Python-From-Begining/blob/main/02_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **NUMPY**

# **Arrays**

In [1]:
import numpy as np

In [2]:
npArray=np.array([1,2,3,4,5,6,7,8])
print(npArray)
npArray2=np.array([1,2,"Hello","3",5,6])
print(npArray2)
print(npArray[2])
print(type(npArray))
print(npArray.shape)
npArray[0]=100
print(npArray)
npArray2[2]=30
print(npArray2)

npArray3=np.array([
    [3,4,5,6,7],
    [1,2,3,4,5]
])
print(npArray3)
print(npArray3[0,3],npArray3[1,4]) # Also npArray3[0][3] is valid

[1 2 3 4 5 6 7 8]
['1' '2' 'Hello' '3' '5' '6']
3
<class 'numpy.ndarray'>
(8,)
[100   2   3   4   5   6   7   8]
['1' '2' '30' '3' '5' '6']
[[3 4 5 6 7]
 [1 2 3 4 5]]
6 5


In [3]:
a = np.zeros((2,2)) # All element is Zero
b = np.ones((3,3,3)) # All element is One
print(f"""Zeros Array is
%s
and Ones Array is
%s"""%(a,b))

Zeros Array is 
[[0. 0.]
 [0. 0.]]
and Ones Array is 
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [4]:
c = np.full((4,4),24) # all element is 24
print(c)
d = np.eye(3,3) # identity Matrix
print(d)
e = np.random.random((3,4))
print(e)


[[24 24 24 24]
 [24 24 24 24]
 [24 24 24 24]
 [24 24 24 24]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.27873899 0.63699864 0.78055076 0.71586594]
 [0.77956348 0.18345573 0.37477812 0.34933979]
 [0.7169029  0.47546528 0.40834133 0.68443119]]


# **Array Indexing**

In [5]:
array1  = np.array([[1,2,3,4,5], [5,6,7,8,9], [9,10,11,12,13],[13,14,15,16,17]])
print(array1[1:,1:3],end="\n\n")
array2 = array1[0:3,1:4]
print(array2,end="\n\n")
print(array2[:2,0:1])
r1=array1[1,:]
r2=array1[0:3,1:4]
print(""" R1 is
%s,
it's shape is
%s
and it's type is
%s
also R2 is
%s,
it's shape is
%s
and it's type is
%s
"""%(r1,r1.shape,type(r1),r2,r2.shape,type(r2)))

[[ 6  7]
 [10 11]
 [14 15]]

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]

[[2]
 [6]]
 R1 is
[5 6 7 8 9],
it's shape is
(5,)
and it's type is
<class 'numpy.ndarray'>
also R2 is
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]],
it's shape is
(3, 3)
and it's type is
<class 'numpy.ndarray'>



In [6]:
print(r2[[0,2,1],[1,2,0]]) # --> [0,1],[2,2] and [1,0]
r3=np.array([r2[0,2],r1[3],r2[2,1]])
print(r3)

[ 3 12  6]
[ 4  8 11]


In [7]:
np.arange(4) # array([0, 1, 2, 3])
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([1,2,3])
c = np.arange(3)
print(a[b,c],end="\n\n") # print(a[[1,2,3],[0,1,2]])
print(a,end="\n\n")
a[[0,1,2,3],[1,2,0,2]] +=10
print(a)

[ 4  8 12]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1 12  3]
 [ 4  5 16]
 [17  8  9]
 [10 11 22]]


# **Boolean Array Indexing**

In [8]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
bool_a = (a%2==0)
print(bool_a)
print(a[bool_a]) # either
print(a[(a%2==0)])


[[False  True False]
 [ True False  True]
 [False  True False]
 [ True False  True]]
[ 2  4  6  8 10 12]
[ 2  4  6  8 10 12]


# **Math**

In [9]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))
print(x*y)
print(np.multiply(x,y))
print(x / y)
print(np.divide(x, y),end="\n\n")
print(np.sqrt(x))

print(x.dot(y),end="\n\n")
print(np.dot(x, y)) # Actual Matrix Multiplication

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


In [10]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]

10
[4 6]
[3 7]


In [11]:

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


# **Broadcasting**
Broadcasting is a powerful NumPy feature that allows arrays of different shapes to be used together in arithmetic operations without explicitly copying or reshaping data.

In [12]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
y = np.array([1,2,3])
z = np.empty_like(x) # # Create an empty matrix with the same shape as x (values are grabage)
print(z)
for i in range(4):
  z[i,:]=x[i,:]+y
print(z)

[[4598692935100074150 4603912793199096715 4605205795802327217]
 [4604623166710304103 4605196903148394956 4595777709511525028]
 [4600423022389100192 4599964766061083286 4604632506789513681]
 [4602236840859526152 4601027643318291590 4604340027631958345]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [13]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
y = np.array([1,2,3])
z = x+y
print(z)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


# **Outer Product**
The outer product of two vectors creates a matrix by multiplying each element of the first vector with each element of the second vector.

In [14]:
v = np.array([1,2,3])
w = np.array([4,5])

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [15]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = np.array([4,5,6,7,8,9,10,11])
print(a)
print(np.reshape(a,(3,4)))
c=np.reshape(a,(3,4))
print(np.reshape(b,(4,2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [16]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = np.array([4,5,6,7])
print(np.reshape(a,(3,4))*b)

[[ 4 10 18 28]
 [20 30 42 56]
 [36 50 66 84]]


In [17]:
x = np.array([[1,2,3], [4,5,6]])
w = np.array([4,5])
v = np.array([1,2,3])
print(x + v)
print(x.T)
print((x.T + w).T)
print(x + np.reshape(w, (2, 1)))
print(x * 2)


[[2 4 6]
 [5 7 9]]
[[1 4]
 [2 5]
 [3 6]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
